### ISSUE TITLE
Weave GitOps identity and access management (IAM)

### ISSUE THREAD

**Issue by foot** [weaveworks/weave-gitops#1089]
We want to build a simple authentication and authorization management service for the WeGO platform. 

**Short description**
As a platform operator I can restrict access to my cluster.

**Acceptance criteria**
- [ ] Users can authenticate via the UI and CLI with a username and password
- [ ] Users can authenticate via the UI and CLI with an OIDC provider
- [ ] Users are impersonated when accessing k8s resources, and so are restricted by user-configured k8s RBAC.

This feature should be feature flagged during development
