### ISSUE TITLE
UI cleanup sizes and colors

### ISSUE THREAD

**Issue by bia** [weaveworks/weave-gitops#1096]
A list of nits, with reference to our new [design system colors](https://www.figma.com/file/gnodK9xtoOahXBqa6ONsA5/Design-System-%2F-Draft?node-id=4%3A6) : 

- [ ] All dark/black text should be `#1A1A1A`, with no transparencies

<img width="1440" alt="Screenshot 2021-11-18 at 13 43 19" src="https://user-images.githubusercontent.com/92439/142422894-a7640e37-c886-4c32-8dfa-433e74a46d76.png">

- [ ] All grey text should be `#737373`, with no transparencies
<img width="1440" alt="Screenshot 2021-11-18 at 14 31 31" src="https://user-images.githubusercontent.com/92439/142424826-7755f508-0ccf-4f54-92f3-f7423de9f98f.png">

- [ ] grey and dark icons should also be `#737373` and `#1A1A1A`
<img width="129" alt="Screenshot 2021-11-18 at 14 43 33" src="https://user-images.githubusercontent.com/92439/142426700-32bb3e01-6c80-48a5-8d50-90b39987d9e0.png">

- [ ] Buttons in color `#00A7CC` should be `#006B8E` ([dark primary color](https://www.figma.com/file/gnodK9xtoOahXBqa6ONsA5/Design-System-%2F-Draft?node-id=4%3A6)) with white semibold capitalised text
<img width="169" alt="Screenshot 2021-11-18 at 14 02 01" src="https://user-images.githubusercontent.com/92439/142421812-e52f83cc-d8fe-4d46-aa7c-9220e6319282.png">

- [ ] Provider dropdown should have a bold label and table width should be equal to tile page width in order to have a smooth transition
![chrome-capture](https://user-images.githubusercontent.com/92439/142419908-5a498964-0f5d-425c-93e9-00e587983161.gif)

- [ ] This random pink slider should be blue
<img width="280" alt="Screenshot 2021-11-18 at 13 53 31" src="https://user-images.githubusercontent.com/92439/142419087-24b35811-6c1e-410d-95e3-7f59a5a17425.png">

- [ ] Menu item marker should be `#00B3EC` instead of `#00d2ff`
<img width="1440" alt="Screenshot 2021-11-18 at 14 27 34" src="https://user-images.githubusercontent.com/92439/142426095-eea2f74c-2ba0-49f6-a248-95df2d83f909.png">

**Comment by joshri** [comment]
Hey @bia!
Does joshua.israel@weave.works have access to the new Figma doc? Can't open it right now to grab the colors. Right now wego core doesn't have that dropdown or any grey/black icons, but everything else should be easy enough!

**Comment by bia** [comment]
cc @AlinaGoaga could you take care of this one?
- [ ] Provider dropdown should have a bold label and table width should be equal to tile page width in order to have a smooth transition
![chrome-capture](https://user-images.githubusercontent.com/92439/142419908-5a498964-0f5d-425c-93e9-00e587983161.gif)

**Comment by joshri** [comment]
My PR (#1145) changes the text, button, and switch colors from this issue in Core with the new colors - my understanding is that those changes will have to be done separately in Enterprise as we don't share the same theme. Leaving the issue open for @AlinaGoaga
