### ISSUE TITLE
Add `gitops add/apply profile/profiles` command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#1109]
### Description
As a weave gitops user
I want to run a command `gitops add/apply profile/profiles` on the CLI
So that I can install a profile

### Scope

- The command should be added in `weave-gitops` and behave similarly to `pctl add` command
- The command should create a PR by default
- The command should use the [git repository setting documented here](https://docs.gitops.weave.works/docs/next/cluster-management/getting-started/#profiles-and-clusters) as the value of `--git-repository` flag from the `pctl` command
- Testing and documentation should be added for the new command in `weave-gitops` 

### Acceptance Criteria
Given that I am a weave gitops user
When I run CLI command `gitops add/apply profile/profiles <profile-name> --cluster <cluster-name> --version=0.0.1 --set port=80 replicas=3 pr-title=my_pr branch=my_branch commit=my_commit`
Then the command should generate the profile installation for the version provided and
Then it should open a PR against my repository and 
I should get a link to the PR on the terminal `Created pull request: <link>`

When I run CLI command `gitops add/apply profile/profiles <profile-name> --cluster <cluster-name>`
And I don't provide the `--version` flag
Then the profile installation should be generated using the latest version of the profile

When I run CLI command `gitops add/apply profile/profiles <profile-name>`
And I use the  `--skip-pr` flag
Then the PR should not be created as default

When I run CLI command `gitops add/apply profile/profiles <profile-name> --cluster <cluster-name>`
And I do not provide `port, replicas, pr-title, branch, commit` flags
Then I should be prompted for input for all of these before the profile is installed

When I run CLI command `gitops add/apply profile/profiles`
And I provide incorrect `<profile-name>` value
Then I should see the error on the terminal

When I run CLI command `gitops add/apply profile/profiles`
And I provide incorrect `<cluster-name>` value
Then I should see the error on the terminal

When I hit the endpoint to install a profile
And I provide valid profile data as part of the request
Then I should get back the `yaml` as a successful response

### Technical Notes
- Create an API so that we can install a profile using both CLI and UI [ UI will not be implemented as part of this ticket] 
- Some of these flags from the current pctl command will become redundant in `weave-gitops`, investigate which ones we need to keep
```
   --pr-remote value             The remote to push the branch to. (default: origin)
   --pr-base value               The base branch to open a PR against. (default: main)
   --pr-repo value               The repository to open a pr against. Format is: org/repo-name.
   --namespace value             The namespace to use for generating resources. (default: default)
   --profile-branch value        The branch to use on the repository in which the profile is. (default: main)
   --config-map value            The name of the ConfigMap which contains values for this profile.
   --profile-repo-url value      Optional value defining the URL of the repository that contains the profile to be added.
   --profile-path value          Value defining the path to a profile when url is provided. (default: <root>)
   ```

**Comment by davidstauffer** [comment]
LGTM.

**Comment by Himangini** [comment]
Check with PE if this is still valid https://github.com/weaveworks/weave-gitops-private/blob/main/docs/adrs/0007-directory-layout.md

**Comment by bigkevmcd** [comment]
I'll clarify this, the `profiles` subdir in the ADR doc is holdover from pre-Helm chart profiles.

Profiles are written to `/.weave-gitops/clusters/<name-of-cluster>/system`

I'll get an update to the ADR done

**Comment by nikimanoledaki** [comment]
- [ ] gitops add profile < profile-name >
- [ ] --name="podinfo"
- [ ] --url https://weaveworks.github.io/profiles-examples 
- [ ] --config-repo ssh://git@github.com/nikimanoledaki/fun-times.git  
- [ ] --chart podinfo
- [ ] alias: gitops **apply** profile
- [ ] alias: gitops add **profiles**
- [ ] --cluster <cluster-name> 
- [ ] --version=0.0.1 
- [ ] --port=80 
- [ ] --replicas=3 
- [ ] --pr-title=my_pr 
- [ ] --branch=my_branch 
- [ ] --commit=my_commit
- [ ] --pr-remote value             The remote to push the branch to. (default: origin)
- [ ] --pr-base value               The base branch to open a PR against. (default: main)
- [ ] --pr-repo value               The repository to open a pr against. Format is: org/repo-name.
- [ ] --namespace value             The namespace to use for generating resources. (default: default)
- [ ] --profile-branch value        The branch to use on the repository in which the profile is. (default: main)
- [ ]  --config-map value            The name of the ConfigMap which contains values for this profile.
- [ ]  --profile-repo-url value      Optional value defining the URL of the repository that contains the profile to be added.
- [ ]  --profile-path value          Value defining the path to a profile when url is provided. (default: <root>)

**Comment by Himangini** [comment]
We'll spit this one into smaller tickets. Also the PRs will be opened against a feature branch

**Comment by Himangini** [comment]
@davidstauffer @sympatheticmoose Can you help us understand the `--replicas` flag, please. What does it do for gitops commands, and do we need it for `gitops add/apply profiles`?

**Comment by Himangini** [comment]
> @davidstauffer @sympatheticmoose Can you help us understand the `--replicas` flag, please. What does it do for gitops commands, and do we need it for `gitops add/apply profiles`?

@josefaworks can you help out with this, please?

**Comment by Himangini** [comment]
> `--replicas=5` is an example of a Key/Value pair of the values.yaml that can be defined. See: https://github.com/weaveworks/weave-gitops/blob/main/cmd/gitops/add/clusters/cmd.go#L49-L50
> 
> ```
> gitops add cluster --from-template <template-name> \
> --profile 'name=foo-profile,version=0.0.1' --profile 'name=bar-profile,values=bar-values.yaml
> ```
> 
> Let me know if that helped.

Adding support for `values.yaml` file to be passed as an option for this command seems a new feature to me and out of scope for this ticket. I'll add a new ticket to track this requirement. Meanwhile, for this ticket, we will skip the implementation of the `--replica` flag cc @josefaworks
