### ISSUE TITLE
[Subtask] Add gitops add command

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#1311]
follow up from #1109

### Description
As a weave gitops user
I want to run a command `gitops add/apply profile/profiles` on the CLI
So that I can install a profile

This subtask adds the remaining flags from the todo 
- [ ]  --pr-title=my_pr
- [ ]  --commit=my_commit
- [ ]  --branch value The branch to merge to. (default: main)

### Scope

- The command should be added in `weave-gitops` and behave similarly to `pctl add` command
- The command should create a PR by default
- The command should use the [git repository setting documented here](https://docs.gitops.weave.works/docs/next/cluster-management/getting-started/#profiles-and-clusters) as the value of `--git-repository` flag from the `pctl` command
- Testing and documentation should be added for the new command in `weave-gitops` 

### Acceptance Criteria
Given that I am a weave gitops user
When I run CLI command `gitops add profile <profile-name> --cluster <cluster-name> --version=0.0.1 --set port=80 pr-title=my_pr branch=my_branch commit=my_commit`
Then the command should generate the profile installation for the version provided and
Then it should open a PR against my repository and 
I should get a link to the PR on the terminal `Created pull request: <link>`

**Comment by Himangini** [comment]
@Himangini check with product/ux what replica is used for?

**Comment by Himangini** [comment]
Use the flags names which are consistent with current implementation since the UX sheet seems to be outdated
