### ISSUE TITLE
Add owner flag in the add command

### ISSUE THREAD

**Issue by luizbafilho** [weaveworks/weave-gitops#144]
**Short description**
As a user, I want to specify the repo `owner` as a flag in the `add` command.

**Acceptance criteria**
- [] user should be able to specify the `--owner` flag when adding a new repo
- [] user should be able to specify the owner by setting `GITHUB_ORG` environment variable.
- [] the command flag should have priority over the environment variable

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._
