### ISSUE TITLE
Set up docs site

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops#156]
**Short description**
As a user I want to read documentation so that I can be successful with weave-gitops.

**Acceptance criteria**
- [ ] Site is hosted publicly
- [ ] source repo is also public
- [ ] automatically versioned along with releases 
- [ ] users can submit pull requests to improve docs
- [ ] basically same coolness as WKP docs site
- [ ] has a landing page
- [ ] getting started guide
- [ ] troubleshooting guide
- [ ] architecture overview
- [ ] cli reference

**Design materials**
see http://docs.wkp.weave.works for the approach

**Work breakdown**
