### ISSUE TITLE
Observability MVP

### ISSUE THREAD

**Issue by JamWils** [weaveworks/weave-gitops#1613]
As a user, I want to be able to see list of my objects in unique ways.  

- [x] As a user, I want to see a list of releases.  I.e. `Kustomizations` and `HelmReleases`.
- [x] As a user, I want to see a list of my sources.  I.e. a list of all sources including `GitRepository`, `HelmRepository`, `HelmChart`, and `Bucket`.
- [x] As a user, I want to be able to view a list of resources that are resolved by a `Kustomization` or `Helm Release`.
- [x] As a user, I want to be able to filter on multiple columns and values for each table.
- [x] As a user, I want to be able to see the dependencies, bi-directional for a specific `Kustomization` or `HelmRelease`.
- [x] As a user, I want to be able to see the events for a particular kustomization, helm release, or source.
- [x] As a user, I want to be able to see the helm chart for a particular `HelmRelease`.

## Get Available Namespaces

As a user, I expect to see the relevant objects listed above.
As a user, I don't expect to be able to access namespaces outside of my RBAC permissions.

Sub epic in progress: https://github.com/weaveworks/weave-gitops/issues/1723

## Sharing Context

As a user, I expect to be able to share a hyperlink with colleagues and they have the same view that I do in terms of applied filters on the page.  As a user, I would expect them to see a different set of objects on the page of their RBAC permissions do not match mine.

As a user, if I given a "detail" page for something I do not have permissions for then I would expect to see an error message letting me know that the page could not be found.

## Pagination

As a user, I would expect to be able to page through a larger list of items. 
As a user, I would expect to be able to toggle the number of items listed on each screen.  For example, I could toggle to show 10, 25, 50, 100, or 200 items per screen and be able to page through it accordingly.

Back end ticket not yet refined: https://github.com/weaveworks/weave-gitops/issues/1697
