### ISSUE TITLE
Epic: Multi-Cluster

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/weave-gitops#1677]
This is the breakdown of work. Some tickets can be done in the same PR, some you may want to tackle separately:

POC can be found here: https://github.com/weaveworks/weave-gitops/pull/1556.

Decision write up here: https://docs.google.com/document/d/1kxcyznya57gAW28_jUU4ZQVffAyrSze7Py_y0T_z6jE/edit#

### Context

- Multi-cluster is *not* a feature of core
- So core cannot have any way to add multiple clusters
- So we will be doing the multi bit in Enterprise
- From core's side we need to:
  - Define the clusters fetcher interface
  - Fulfil that interface by adding a single, in-memory cluster to a pool which is added to the context (basically doing what we do now, but putting the client somewhere else).
- From enterprise's side we will:
  - First implement a temporary ConfigMap based fulfilment of the fetcher interface (to unblock anyone waiting on this)
  - Then (when the official CRDs become available) replace the temporary solution and fulfil the fetcher interface using those CRDs.

### Work to be done in Core
- [x] https://github.com/weaveworks/weave-gitops/issues/1600
- [x] https://github.com/weaveworks/weave-gitops/issues/1676
- [x] https://github.com/weaveworks/weave-gitops/issues/1675
- [x] https://github.com/weaveworks/weave-gitops/issues/1674
- [x] https://github.com/weaveworks/weave-gitops/issues/1673
- [x] https://github.com/weaveworks/weave-gitops/issues/1672
- [x] https://github.com/weaveworks/weave-gitops/issues/1859

### Work to be done in Enterprise

- [x] ~https://github.com/weaveworks/weave-gitops/issues/1690~
- [x] https://github.com/weaveworks/weave-gitops/issues/1691
- [ ] https://github.com/weaveworks/weave-gitops/issues/2000
