### ISSUE TITLE
Cross-namespace Queries

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/weave-gitops#1723]
We want weave-gitops to be a "single pane of glass" for users' gitops environments. Therefore, we need to display resources across namespace within a single page.

Our solution also needs to take multi-cluster querying into account. We will need to query resources in each namespace, in each cluster.

- [x] https://github.com/weaveworks/weave-gitops/issues/1724
- [x] https://github.com/weaveworks/weave-gitops/issues/1725
- [x] https://github.com/weaveworks/weave-gitops/issues/1726
- [x] placeholder: query other objects from namespaces
- [x] placeholder: cache user access record with TTL
- [x] placeholder: update namespaces watcher to watch across all clusters (being done somewhere else)

**Comment by Callisto13** [comment]
This is done as of https://github.com/weaveworks/weave-gitops/pull/1952
