### ISSUE TITLE
Add Flux bootstrap commands for other providers

### ISSUE THREAD

**Issue by chanwit** [weaveworks/weave-gitops#2689]
- [x] `bootstrap gitlab` in PR #2701 
  - [ ] `bootstrap bitbucket-server` PR #2709
  - [ ] `bootstrap git` PR #2715
