### ISSUE TITLE
Support dark mode in the UI - OSS

### ISSUE THREAD

**Issue by makkes** [weaveworks/weave-gitops#2948]
As a UI user I want to be able to change the colors to a light-on-dark theme (dark mode). As an option the color scheme (light or dark mode) should automatically be chosen based on [the system/browser setting](https://caniuse.com/?search=prefers-color-scheme).

Earlier designs:
![20220602Application Table View - Dark Mode](https://user-images.githubusercontent.com/19860021/199690530-abd94312-fd4b-42e7-938b-3ee4f5b37f5a.png)

**Comment by sympatheticmoose** [comment]
assigning to Sunglow for now to have on our backlog, but this is not currently prioritised for this quarter, cc @JamWils

**Comment by JamWils** [comment]
For any people following this issue, design is working on all of the pieces for this support.

**Comment by makkes** [comment]
@JamWils Do we have an update on whether this will make it into one of the next releases?

**Comment by LappleApple** [comment]
### Background
- **Impacted users:** All users of Weave GitOps 
- **Mission/Objective:** Allow users to set their color schemes based on their preferences.
- **Scope:** This issue focuses on what is required to release the Dark Mode MVP. We'll describe future iterations in separate GH issues.

### Acceptance Criteria for V 1.0
- [ ]  As a Weave GitOps user, I will be able to choose my UI color settings and select between light mode, dark mode and system mode.
- [ ]  As a Weave GitOps user, I can only select one color mode at a time.
- [ ]  As a Weave GitOps user, I should be able to revert any changes made by simply choosing a different color mode.

### Additional Reqts
- [ ]  There should be a brief description for system mode (maybe via a tooltip that works on hover)

### Relevant PRs and Issues
- [ ] #3670 
- [ ] #3677 
      - [ ]  Adds dark mode switch that remembers your selection plus dark mode design.
      - [ ]  Footer JSX and styling changed to have background inside content.
      - [ ]  Sign in background changed and animation removed.
      - [ ]  Makes ton of small changes to accommodate dark mode where we weren't prepared
- [ ] #3681 
- [ ] #3682 
- [ ] #3683

**Comment by LappleApple** [comment]
@yiannistri @joshri Closing per our refinement. Great work!
