### ISSUE TITLE
Image Automation 

### ISSUE THREAD

**Issue by enekofb** [weaveworks/weave-gitops#3156]
At the back of https://www.notion.so/weaveworks/Image-Automation-in-Weave-GitOps-39e01d2cd5e04538ace55e30c9d732ff 

This epic to enable users to view all Image Automation objects on a cluster in the Weave GitOps Dashboard. To do this we will need:
- [x] #3215
- [x] #3216
- [x] #3217
- [x] #3219 
- [x] #3220 
- [x] #3221 
- [x] #3222 
- [x] #3223 
- [x] FE: As a user, when I click on a given ImageUpdateAutomation, ImagePolicy, or ImageRepository, I am taken to a details page for the given object.
- [x] #3259 
- [x] #3260 
- [x] #3261 
- [x] FE: As a user, if I do not have the ImageReflector and ImageUpdate Controller installed on any cluster I am presented with an onboarding message
- [x] FE: As a user, if I do not have the ImageReflector and ImageUpdate Controller installed on all my clusters I am not presented with an error.

Considerations:
- [x] FE: all pages should auto refresh with new data
- [x] FE: all details pages include standard details, events, yaml tabs
- [ ] FE/BE: details pages should provide suspend and resume actions

Designs: https://balsamiq.cloud/s5qd59g/pgh2m3r/r9312

Notes:
- The Link for Last commit can be a fast follow depending on ease of extracting from the referenced Source.
- There may be value in being able to extract the image registry from the image field on ImageRepository objects and allow a user to i.e. filter for all dockerhub images to understand potential rate limiting. We could explore this further as a follow up to the ImageRepository table.
- Marker structure for Image Policy details: `# {”$imagepolicy”: “<image-policy-namespace>:<image-policy-name>”}`  - example = `# {"$imagepolicy": "flux-system:podinfo"}`
