### ISSUE TITLE
Checklist: streamline page flows for OSS and Enterprise (intro/install/get started)

### ISSUE THREAD

**Issue by LappleApple** [weaveworks/weave-gitops#3739]
This issue proposes flows that will streamline intro/install/deploy steps for users and enables us to untangle Weave GitOps Open Source from Weave GitOps Enterprise pages. It also calls for removing duplicate pages and paths that cause confusion. I've structured this as a checklist to help organize related work.

When I refer to page titles ("remove the [X] page"...) in these steps, I am using *only* current titles and not incorporating any of my suggested new titles.

## Weave GitOps Introduction

- [x] Ensure that [this intro page](https://docs.gitops.weave.works/docs/next/intro/) appears in the left-side menu as “Introducing Weave GitOps”.

## Weave GitOps Open Source pages flow, titles

- [x] Remove the [Getting Started](https://docs.gitops.weave.works/docs/next/getting-started/intro/) page.
- [x]  Remove the [0. Install Weave GitOps](https://docs.gitops.weave.works/docs/next/installation/) page.
- [x]  Ensure that the [installation/weave-gitops](https://docs.gitops.weave.works/docs/next/installation/weave-gitops/) page appears as “Step 1: Install Weave GitOps Open Source” in the left-side menu.
- [x] Ensure that [Explore the GitOps UI](https://docs.gitops.weave.works/docs/next/getting-started/ui/) appears in the left-side menu as “Step 2: Explore the UI”.
- [x]  Ensure that the [Deploy an Application](https://docs.gitops.weave.works/docs/next/getting-started/deploy/) page appears in the left-side menu as “Step 3: Deploy an Application”.
- [x] Ensure that the [Introducing GitOps](https://docs.gitops.weave.works/docs/next/intro/) links directly to the [Installing Weave GitOps OSS](https://docs.gitops.weave.works/docs/installation/weave-gitops/) page. 
- [x] Ensure that the [Installing Weave GitOps OSS](https://docs.gitops.weave.works/docs/installation/weave-gitops/) page links directly to the [Explore the GitOps UI](https://docs.gitops.weave.works/docs/next/getting-started/ui/) page.
- [x]  Ensure that the [Explore the GitOps UI](https://docs.gitops.weave.works/docs/next/getting-started/ui/) page links directly to the [Deploy an Application](https://docs.gitops.weave.works/docs/next/getting-started/deploy/) page.

## Weave GitOps Enterprise pages flow, titles

- [x]  Ensure that the [Introducing GitOps](https://docs.gitops.weave.works/docs/next/intro/) links directly to the [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/) page.
- [x] Ensure that the [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/) page appears in the left-side menu as “Intro: Weave GitOps Enterprise”.
- [x] Ensure that the [Weave GitOps Enterprise](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/) page appears in the left-side menu as “Installing Weave GitOps Enterprise”.
- [x]  Ensure that the [Enterprise Edition page](https://docs.gitops.weave.works/docs/next/intro-ee/) links directly to the [Weave GitOps Enterprise](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/) page. 
- [x]  Retitle the [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/) page “Intro to Weave GitOps Enterprise”.
- [x]  Ensure that the [Weave GitOps Enterprise](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/) page appears as “Installing Weave GitOps Enterprise” in the left-side menu.
- [x]  Ensure that the [Installing Weave GitOps Enterprise](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/) links directly from the [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/) page.
- [x]  Ensure that the [Airgapped Environments](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/airgap/) page links directly from the [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/) page.
- [x]  Ensure that the [AWS Marketplace](https://docs.gitops.weave.works/docs/installation/aws-marketplace/) page links directly from the [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/) page.
- [x]  Ensure that the [Releases](https://docs.gitops.weave.works/docs/releases/) page appears as “Enterprise Releases” in the left-side menu.
- [x]  Remove the link connecting the [Installing Weave GitOps Enterprise](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/) page with the [Airgapped Environments](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/airgap/) page.

## Sections/buckets of related pages, and new paths

This section shows what belongs in the Intro, OSS "Getting Started", and Enterprise "Getting Started" sections. It enforces consistent URLs.

### Weave GitOps
- [x]   [Weave GitOps](https://docs.gitops.weave.works/docs/intro/): from `/docs/intro` ==> `docs/intro-weave-gitops/`
- [x]  Remove `/installation/` folder (will be left empty)

### OSS: from `/docs/intro/` ==> `/docs/open-source/getting-started`
- [x]   create `open-source` folder in directory
- [x]   [OSS install](https://docs.gitops.weave.works/docs/next/installation/weave-gitops/): from `/docs/next/installation/weave-gitops/` ==> `/docs/open-source/getting-started/install-OSS`
- [x]   [Explore the UI](https://docs.gitops.weave.works/docs/getting-started/ui/): from `/docs/getting-started/ui/` ==> `/docs/open-source/getting-started/ui-OSS/`
- [x]   [Deploy an Application](https://docs.gitops.weave.works/docs/getting-started/deploy/): from `/docs/next/getting-started/deploy/` ==> `/docs/open-source/getting-started/deploy-OSS/`

### Enterprise: from no clear path to `/docs/enterprise/getting-started/`
- [x]   create `enterprise` folder in directory
- [x]   [Enterprise Edition](https://docs.gitops.weave.works/docs/next/intro-ee/): from `docs/next/intro-ee/` ==> `/docs/enterprise/getting-started/intro-enterprise`
- [x]   [Weave GitOps Enterprise](https://docs.gitops.weave.works/docs/next/installation/weave-gitops-enterprise/): from `/docs/next/installation/weave-gitops-enterprise/index` ==> `/docs/enterprise/getting-started/install-enterprise`
- [x]   [Airgap Environments](https://docs.gitops.weave.works/docs/installation/weave-gitops-enterprise/airgap/): from `/docs/installation/weave-gitops-enterprise/airgap/` ==> `/docs/enterprise/getting-started/install-enterprise-airgap/`
- [x]   [AWS Marketplace](https://docs.gitops.weave.works/docs/next/installation/aws-marketplace/): from `/docs/installation/weave-gitops-enterprise/aws-marketplace//` ==> `/docs/enterprise/getting-started/aws-marketplace//`
- [x]   [Releases](https://docs.gitops.weave.works/docs/releases/): from `/docs/releases/` ==> `/docs/enterprise/releases-enterprise/`
