### ISSUE TITLE
Suspend/resume/reconcile Image Repositories

### ISSUE THREAD

**Issue by yiannistri** [weaveworks/weave-gitops#3820]
**Short description**
As a application developer I want to be able to suspend/resume/reconcile Image Repositories so that I don't have to use the Flux CLI to achieve that.

These operations are currently missing from the UI.

**Acceptance criteria**
- [x] Image Repositories table shows a list of checkboxes that allows a user to select one or more resources
- [x] There's a checkbox at the table header that allows a user to select all resources that appear in the table
- [x] There is a Sync button that allows a user to force reconciliation for the selected resources
- [x] There is a Pause button that allows a user to suspend selected resources
- [x] There is a Resume button that allows a user to resume selected resources

**Work breakdown**
- [ ] #3821
