### ISSUE TITLE
[Umbrella] Meet the OpenSSF's best practices reqts for the "Passing" badge

### ISSUE THREAD

**Issue by LappleApple** [weaveworks/weave-gitops#3978]
As a Weave GitOps OSS user, I would like to be able to see that the project has received a passing OpenSSF grade, so I can be more confident in its quality and stability.

Many OSS projects, including Flagger and Flux, apply the Open Source Security Foundation (OpenSSF)'s [best practices](https://bestpractices.coreinfrastructure.org/en/criteria/0) to gain/retain user trust and as part of their project governance activities. 

**TODOs:**
- [x] Do spike to document which criteria Weave GitOps already fulfills ([see link](https://www.bestpractices.dev/en/projects/7820/edit))
- [x] The project MUST have evidence that the [test_policy](https://www.bestpractices.dev/en/projects/7820#test_policy) for adding tests has been adhered to in the most recent major changes to the software produced by the project.
- [x] It is SUGGESTED that this policy on adding tests (see [test_policy](https://www.bestpractices.dev/en/projects/7820#test_policy)) be documented in the instructions for change proposals.
- [x] The project MUST enable one or more compiler warning flags, a "safe" language mode, or use a separate "linter" tool to look for code quality errors or common simple mistakes, if there is at least one FLOSS tool that can implement this criterion in the selected language.
- [x]  The project MUST address warnings.
- [x] It is SUGGESTED that projects be maximally strict with warnings in the software produced by the project, where practical. 
- [x] It is SUGGESTED that static source code analysis occur on every commit or at least daily. [static_analysis_often]
- [x] It is SUGGESTED that at least one dynamic analysis tool be applied to any proposed major production release of the software before its release.
- [x]  It is SUGGESTED that if the software produced by the project includes software written using a memory-unsafe language (e.g., C or C++), then at least one dynamic tool (e.g., a fuzzer or web application scanner) be routinely used in combination with a mechanism to detect memory safety problems such as buffer overwrites. If the project does not produce software written in a memory-unsafe language, choose "not applicable" (N/A). 
- [x] It is SUGGESTED that the project use a configuration for at least some dynamic analysis (such as testing or fuzzing) which enables many assertions. In many cases these assertions should not be enabled in production builds. 
- [x] Application filed using generic bot email for team
- [x] Add badge to Readme https://github.com/weaveworks/weave-gitops/pull/4014

AC: Receive the [Passing badge](https://bestpractices.coreinfrastructure.org/en/criteria/0).

**Comment by LappleApple** [comment]
Achievement unlocked.
