### ISSUE TITLE
Migrate deployment of our documentation site over to Netlify

### ISSUE THREAD

**Issue by Himangini** [weaveworks/weave-gitops#4117]
**Short description**
As a Developer I want to migrate the deployment of our documentation site over to Netlify from GCP so that 
I can
- simplify the deployment process
- speed up deployment time and reduce costs
- help get rid of old version folders being served from the bucket even when they are deleted from our repository
- improve developer productivity since deploy previews over pull requests will no longer take several minutes

Acceptance criteria
- [ ] Add a new workflow for documentation deployment for Netlify
- [ ] Create and setup the documentation site over Netlify
- [ ] Setup relevant env vars, deploy keys, domains etc., for production deploys
- [ ] Make the switch seamless and avoid downtime

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by casibbald** [comment]
wont do, requires commercial license
