### ISSUE TITLE
install prometheus and configure to capture metrics from flux components (profiles)

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#60]
**Short description**
As an SRE I want to query metrics from gitops so that I can use it as an aid in troubleshooting my wego environment

**Acceptance criteria**
- [ ] prometheus is installed
- [ ] user can query metrics from SC, HC, NC, KC
- [ ] manifest(s) for the installed prometheus are in the platform repo (or folder in the monorepo case)  ("platform apps"?)

**Design materials**
- WEP See TBD

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
I would like to close this as out-of-scope for Weave GitOps Core.

**Comment by markramm** [comment]
I don't think this is out of scope for weave gitops core, but another team may be working on the "observability" _profile_ which will (I think) be a plugin for weave gitops core.    

The most requested feature of weave cloud is the timeline view, and I think that should be an (optional, but installed by default) part of what makes weave gitops core more powerful/interesting/k8s native than other gitops tools.
