### ISSUE TITLE
deploy an app into two different environments with changes between them

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#65]
**Short description**
As a SRE I want to deploy MCCP into dev using sqlite and into UAT with postgress so that I can use gitops across environments

**Acceptance criteria**
- [ ] Deploy MCCP v1 in dev with slqlite and using a shared config repo deploy in staging with external DB
- [ ] single configuration repo with both environments 
- [ ] all manifests in git

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by palemtnrider** [comment]
Closing - duplicate of #74
