### ISSUE TITLE
Port forward to the wego app deployed in the cluster

### ISSUE THREAD

**Issue by josecordaz** [weaveworks/weave-gitops#652]
**Short description**
As a user, I want to access the wego UI without having to expose it through an Ingress controller. So I need a command that will map a local port to Wego app in the cluster.

**Acceptance criteria**
- [ ] I can run `gitops ui proxy --port 8080`, call a local port and get access to wego ui
- [ ] It should print a message that looks like: `Access Weave Gitops UI at http://localhost:8080` 
- [ ] The terminal should hang waiting to be canceled

**Design materials**
- https://gianarb.it/blog/programmatically-kube-port-forward-in-go

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jpellizzari** [comment]
As this is written, it doesn't really say what we are trying to accomplish. We want to "proxy" into the cluster to expose the WeGO UI+API on a local port so the user can interact with the UI without exposing it to the public internet.

@luizbafilho Can we do that with `controler-runtime/client`? Or do we need some other mechanism?

**Comment by luizbafilho** [comment]
yes, we should: https://gianarb.it/blog/programmatically-kube-port-forward-in-go
