### ISSUE TITLE
CLI --dry-run option to `wego add`

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#66]
**Short description**
As a SRE I want to see what configuration wego would apply to the cluster for a particular commit --  without it actually performing any actions so that I can verify what manifests, repositories, secrets, etc will be created 

**Acceptance criteria**
- [ ] issuing --dry-run doesn't modify my cluster
- [ ] issuing --dry-run doesn't create or modify any repositories 
- [ ] displays manifests that will be added to my cluster and repo
- [ ] prints the steps that would be performed without the --dry-run flag

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] Separate out generation of manifests so that they can be displayed rather than applied
- [ ] Display output
