### ISSUE TITLE
Weave GitOps CLI support for Windows

### ISSUE THREAD

**Issue by sympatheticmoose** [weaveworks/weave-gitops#663]
As per the stack overflow [survey](https://insights.stackoverflow.com/survey/2021#section-most-popular-technologies-operating-system) (and others) - Windows is an important and well-adopted operating system. If we want to help as many developers as possible adopt GitOps through our product - we need to provide and support our CLI on Windows.

We should:

- [ ] provide a windows binary
- [ ] figure out appropriate testing strategy
- [ ] investigate adding a windows machine to our CI
- [ ] provide a Chocolatey package

**Comment by kingdonb** [comment]
Was this closed because support is added, or has it been taken off the roadmap?

Windows support is a common question, we should leave a breadcrumb to some instructions for how to use the Weave GitOps CLI with WSL, if that's the recommended method.

**Comment by sympatheticmoose** [comment]
I believe this was likely closed by mistake as the team focussed on changes which have now merged. Re-opening as this is still on the radar.

**Comment by LappleApple** [comment]
Hey @kingdonb, it's been a while since anyone commented on this issue -- what do you think we should do now/next, many months later? Still the same recommendation, or something new/different?

**Comment by kingdonb** [comment]
If there is no one to own the GitOps CLI for Windows, and one hasn't been produced yet, then I think the next best thing is to document the WSL path. I haven't been a windows user for a while, so I'm not the best person to decide the path here. But if there are any blockers to producing and testing the Windows CLI, I'd love to see them enumerated.

I think we could try cross-compiling and just put one out there, but I don't think it's entirely appropriate to take the "let any users report the bugs" approach unless we have some users we can point at who are using it with any degree of success.

@juozasg might be able to help us as a user

**Comment by d3287t328** [comment]
This would still be a nice to have. I have a connectivity issue to an environment that requires a windows vpn and WSL is broken for me.

**Comment by DeoEsor** [comment]
+1
