### ISSUE TITLE
UI dry run ability

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#67]
**Short description**
As a SRE I want to see what wego will do without it actually performing any actions so that I can verify what manifests, repositories, secrets, etc will be created 

**Acceptance criteria**
- [ ] using dry run mode doesn't modify my cluster
- [ ] using dry run mode doesn't create or modify any repositories 
- [ ] displays manifests that will be added to my cluster and repo
- [ ] prints the steps that would be performed without using dry run mode

**Design materials**
- Screenshots
- Design diagrams
- WEP 
- PR/FAQ

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by markramm** [comment]
If this is a helm chart can we tell what it will do?

**Comment by jpellizzari** [comment]
Closing as part of an issue cleanup effort discussed with @JamWils and @markramm
