### ISSUE TITLE
Use repo created by another team/process

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#75]
**Short description**
As a App developer I want to use wego with a repo created by my corp IT so that wego doesn't require permissions to create a repo

**Acceptance criteria**
- [ ] blank repo before running wego
- [ ] post running wego, my repo has the proper directory layout
- [ ] add an app to the repo, it gets deployed into my cluster.

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by palemtnrider** [comment]
Closed as it is covered by other stories and this is the default behavior now as wego doesn't create repos.
