### ISSUE TITLE
Add remove/delete app subcommand to the beta command 

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#846]
**Short description**
As a developer, I want to remove an application from a cluster so that I have parity with non-beta commands.

**Acceptance criteria**
- [ ] Application is removed from the cluster Kustomization file
- [ ] Deploy keys used solely for this application are removed
- [ ] Application remove can be a PR 
- [ ] Application remove can be a direct commit to the main branch
- [ ] Application directory is removed if flag (---TBD) is passed and the application is not longer in any clusters

**Design materials**
- ADR for directory layout

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._
