### ISSUE TITLE
CLI: Show the Application Deployment 

### ISSUE THREAD

**Issue by markramm** [weaveworks/weave-gitops#88]
Show the status of all the objects in the application from the CLI. 

`wego status application <name>` or something like that should show the current deployment status of each of the gitops goals that are a part of that application. 

**Acceptance criteria**
- [x] wego CLI status call shows if my app has been sync'd
- [x] wego CLI status call shows if my app has been processed through the kustomize controller (if my app is kustomize based)
- [x] wego CLI status call shows if my app has been processed through the helm controller (if my app is helm based)
- [ ] wego CLI displays any errors my app received in the GitOps runtime
- [x] wego CLI displays last time my app was successfully deployed

**Design materials**
- UX

**Work breakdown**
(optional)Task breakdown of the work
- [ ]  Check status of all flux components driving application in cluster (source, helm, kustomize controllers)
- [ ] Display results to user via CLI

Posslbily Later:
Task: Determine which resources in the system were installed by WeGO
Task: Extract current status from each resource - deployment successful, health checks successful
Task: Display results to user

**Comment by markramm** [comment]
Try to show the actual status of the objects flux is deploying, did the get the new version, have the readiness and liveness probes succeeded?
