### ISSUE TITLE
Status an application via the CLI

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/weave-gitops#94]
**Short description**
As a app developerI want to view the status of my application in the GitOps Runtime so that I can troubleshoot where in the GitOps process my application is.

**Acceptance criteria**
- [ ] wego CLI status call shows if my app has been sync'd
- [ ] wego CLI status call shows if my app has been processed through the kustomize controller (if my app is kustomize based)
- [ ] wego CLI status call shows if my app has been processed through the helm controller (if my app is helm based)
- [ ] wego CLI displays any errors my app received in the GitOps runtime
- [ ] wego CLI displays last time my app was successfully deployed

**Design materials**
- UX

**Work breakdown**
(optional)Task breakdown of the work
- [ ] _create X_
- [ ] _design X_
- [ ] _..._

**Comment by jrryjcksn** [comment]
Duplicate of 88
